# Generated by Django 3.1.6 on 2021-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('publish_year', models.IntegerField()),
                ('age_group', models.IntegerField(choices=[(0, '0-7'), (1, '8-11'), (2, '12-17'), (3, '+18')])),
                ('downloaded_times', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
