# Generated by Django 3.1.6 on 2021-02-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210221_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='image.png', upload_to='book_cover_iamge'),
        ),
        migrations.AlterField(
            model_name='book',
            name='age_group',
            field=models.IntegerField(choices=[(0, '0+'), (1, '7+'), (2, '13+'), (3, '18+')]),
        ),
    ]
