# Generated by Django 3.1.6 on 2021-03-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210301_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='image.png', upload_to='user_avatar'),
        ),
    ]
