# Generated by Django 3.1.6 on 2021-03-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(default=None, to='books.Book'),
        ),
    ]
