# Generated by Django 3.1.6 on 2021-03-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210301_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
