# Generated by Django 3.1.6 on 2021-03-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210306_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_group',
            field=models.CharField(choices=[(0, '0+'), (1, '7+'), (2, '13+'), (3, '18+')], max_length=5),
        ),
    ]
